# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 11:55
from __future__ import unicode_literals

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=200)),
                ('menu_url', models.CharField(max_length=200)),
                ('menu_no', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opweb.Menus')),
            ],
            bases=(models.Model, django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('create_time', models.DateField(auto_now_add=True)),
                ('telphone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
