# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opweb', '0002_menus_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='parent',
            field=models.ForeignKey(default=b'0', null=True, on_delete=django.db.models.deletion.CASCADE, to='opweb.Menus'),
        ),
    ]
